server:
  port: 8090


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    lease-renewal-interval-in-seconds: 1 #하트비트 인터벌
    lease-expiration-duration-in-seconds: 2 # 디스커버리는 서비스 등록 해제 하기 전에 마지막 하트비트에서부터 2초 기다림



spring:
  application:
    name: apiGateway-service
  cloud:
    gateway:
      routes:
        - id: Eureka-Post
          uri: lb://EUREKA-POST
          predicates:
            - Path=/posts/**
        - id: Eureka-UserGroup
          uri: lb://EUREKA-USERGROUP
          predicates:
            - Path=/users/**
        - id: Eureka-Alarm
          uri: lb://EUREKA-ALARM
          predicates:
            - Path=/alarms/**
